### ISSUE TITLE
Helm repository location?

### ISSUE THREAD

**Issue by stuart-c-moore** [GameBench/web-dashboard-helm-chart#1]
Hi,

Are there plans to put this helm chart into a helm repository?

https://helm.sh/docs/topics/chart_repository/

This would simplify our automation considerably. In particular we are using terraform, so it would be great if we could just use the `helm_repository` resource:

https://www.terraform.io/docs/providers/helm/d/repository.html

**Comment by emslade** [comment]
Good idea! I'll take care of it.

**Comment by emslade** [comment]
Hi,

You can now do the following:

```
helm repo add gb-helm-charts https://gb-helm-charts.storage.googleapis.com/
helm install gb-helm-charts/gamebench
```
